---
- hosts: hypervisor
  roles:
    - hypervisor

- hosts: localhost
  roles:
    - ceph

- hosts: openstack-nodes
  roles:
    - openstack-node

- hosts: install-server
  roles:
    - install-server
